@extends('layouts.print')

@section('title', 'OPD Slip - ' . $consultation->token_number)

@section('content')
{{-- 1. Top blank (letterhead area) --}}
<div style="height: 2.5in;"></div>

{{-- 3. Printed section (Clean and Aligned) --}}
<div class="content"
    style="font-family: 'Courier New', Courier, monospace; font-size: 11pt; border-bottom: 1px dashed #000; padding-bottom: 20px;">

    {{-- Row 1 --}}
    <div style="display: flex; justify-content: space-between; margin-bottom: 12px;">
        <div style="width: 65%;">Name: <strong style="font-size: 13pt; text-transform: uppercase;">{{
                $consultation->patient->full_name }}</strong></div>
        <div style="width: 30%; text-align: right;">Date: <strong>{{ $consultation->consultation_date->format('d/m/Y')
                }}</strong></div>
    </div>

    {{-- Row 2 --}}
    <div style="display: flex; gap: 40px; margin-bottom: 12px;">
        <div>Age: <strong>{{ $consultation->patient->age }}</strong></div>
        <div>Gender: <strong>{{ $consultation->patient->gender }}</strong></div>
        <div>UHID: <strong>{{ $consultation->patient->uhid }}</strong></div>
    </div>

    {{-- Row 3 --}}
    <div style="display: flex; gap: 40px; margin-bottom: 12px;">
        <div style="width: 45%;">Weight: <strong>{{ $consultation->weight ?? '--' }} kg</strong></div>
        <div style="width: 45%;">Temp: <strong>{{ $consultation->temperature ?? '--' }} °F</strong></div>
    </div>

    {{-- Row 4 --}}
    <div style="display: flex; justify-content: space-between; margin-bottom: 12px;">
        <div style="width: 45%;">Token No: <strong
                style="font-size: 16pt; border: 1px solid #000; padding: 2px 8px;">#{{
                str_pad($consultation->token_number, 2, '0', STR_PAD_LEFT) }}</strong></div>
        <div style="width: 45%; text-align: right;">Valid Upto: <strong style="color: #000;">{{
                $consultation->valid_upto->format('d/m/Y') }}</strong></div>
    </div>

    {{-- Row 5 --}}
    <div style="display: flex; justify-content: space-between; margin-bottom: 12px;">
        <div style="width: 45%;">OP Charge: <strong>₹{{ number_format($consultation->fee, 0) }}</strong></div>
        <div style="width: 50%; text-align: right;">Payment: <strong>{{ $consultation->payment_method }}</strong></div>
    </div>

</div>

{{-- 4. Empty space for doctor writing --}}
<div style="margin-top: 30px; font-style: italic; color: #eee; font-size: 30pt; font-weight: 900; opacity: 0.5;">
    Rx
</div>

<div class="footer">
    <p style="font-size:8pt; color:#64748b; margin:0">Generated by HMS Portal | Please bring this slip for follow-up
        within 7 days.</p>
</div>
@endsection